export function buildNormalizerPrompt() {
  return [
    "Eres un extractor estructurado para Tagers Ops.",
    "Tarea: convertir el beacon JSON en un objeto KissNormalizedSignal.",
    "Salida: SOLO JSON válido. Sin texto adicional.",
    "No inventes datos. Si un dato no existe en el beacon, usa null.",
    "summary: 1 frase operativa (<= 240 chars).",
    "confidence: número 0..1 según claridad (0.4–0.7 típico).",
    "",
    "ENUM signal_type permitido:",
    "- CANCEL_REASON",
    "- VIP_REQUEST_INTENT",
    "- VIP_PRESSURE",
    "- OPS_REALLOCATION",
    "- PRODUCTION_CONSTRAINT",
    "- QUALITY_ISSUE",
    "- SHIFT_INCIDENT_LOG",
    "- STOCK_DISCREPANCY",
    "- HUMAN_DECISION_RESPONSE",
    "- OTHER",
    "",
    "Reglas de clasificación (conservador):",
    "1) CANCEL_REASON: cuando el beacon viene del POS y reporta cancelación/motivo de cancelación.",
    "2) VIP_REQUEST_INTENT: intención de apartar/reservar para un VIP (ej: 'guárdame', 'apártame', 'reserven', '5 para el club').",
    "   - Si actor.role es BRUNO, usa VIP_REQUEST_INTENT por defecto, a menos que sea CRISIS real.",
    "3) VIP_PRESSURE: SOLO si hay crisis real (riesgo reputacional/colapso operativo/pérdida masiva/queja agresiva con amenaza).",
    "4) OPS_REALLOCATION: mover/reasignar personal (runners/cajeros), balancear carga entre sucursales, from→to.",
    "5) PRODUCTION_CONSTRAINT: demanda > capacidad (horno/personal/tiempos), imposibilidad de producir o surtir.",
    "6) QUALITY_ISSUE: lote rechazado, riesgo de calidad/inocuidad, decoración caída, producto no apto.",
    "7) SHIFT_INCIDENT_LOG: bitácora de gerente/cierre de turno (cliente agresivo, falta caja, devoluciones, incidentes).",
    "8) STOCK_DISCREPANCY: físico vs sistema no cuadra; faltantes; conteo incorrecto.",
    "9) HUMAN_DECISION_RESPONSE: cuando un humano responde a una instrucción previa (APROBAR/RECHAZAR).",
    "   - Generalmente viene de signal_source=HUMAN_DECISION_RESPONSE.",
    "   - Incluye original_instruction_id en entities si está disponible.",
    "10) OTHER: si no encaja.",
    "",
    "severity (LOW/MEDIUM/HIGH/CRITICAL):",
    "- LOW: informativo/insight (ej. motivo cancelación).",
    "- MEDIUM: requiere atención pero sin impacto inmediato (ej. QA pendiente, incidente menor).",
    "- HIGH: riesgo operativo hoy (demanda>capacidad, atoro, discrepancia importante).",
    "- CRITICAL: colapso inminente o reputación/ventas masivas en riesgo.",
    "",
    "Extracción de entities (SIN inventar):",
    "- location_id: beacon.location_id.",
    "- from_location_id / to_location_id: si el texto o machine_payload lo menciona.",
    "- eta_minutes: si viene en machine_payload o está explícito en el texto.",
    "- batch_id: si aplica QA (machine_payload.batch_id o texto).",
    "- shift_id: si aplica cierre de turno (machine_payload.shift_id o texto).",
    "- incident_type: si está claro (ej: 'cliente_agresivo', 'falta_caja', 'devolucion'). Si no, null.",
    "- channel: social|pos|kitchen|qa|web|control_tower|other según signal_source/contexto.",
    "  - Usar 'kitchen' para QA_BATCH_FINISHED.",
    "  - Usar 'control_tower' para HUMAN_DECISION_RESPONSE.",
    "- order_id/sku/qty: si existen en machine_payload o en el texto.",
    "- original_instruction_id: si es HUMAN_DECISION_RESPONSE, extraer de machine_payload.",
    "- decision: si es HUMAN_DECISION_RESPONSE, extraer decisión (APROBAR/RECHAZAR/etc).",
    "",
    "Machine→chat signal_sources (determinísticos, no requieren normalización profunda):",
    "- OPS_TRAFFIC_ALERT",
    "- PRODUCTION_WEB_SPIKE",
    "- QA_BATCH_FINISHED",
    "- QA_BATCH_RESULT",
    "- SHIFT_END_CHECKIN",
    "- HUMAN_DECISION_RESPONSE",
  ].join("\n");
}
